define(['app', 'services/vilidateService', 'services/httpService'], function (app, vilidate, httpService) {
    app.controller('accountCtrl', ['$scope', "$rootScope", "$state","$timeout",
        function ($scope, $rootScope, $state,$timeout) {
            if(!sessionStorage.getItem("userId")){
                $state.go("login");
                return;
            }
            $scope.removeRight();
        	var str="user/";
        	$scope.modify=0;
            $scope.editSuc=0;
        	$scope.userInfo={};
        	$scope.init=function(){
        		$scope.modify=0;
        		$scope.pwd={
	        		old:"",
	        		new:"",
	        		again:""
	        	};
	        	$scope.pwdVi.new=0;
	        	$scope.pwdVi.old=0;
	        	$scope.pwdVi.again=0;
	        	$scope.pwdVi.again_1=0;
                $scope.editSuc=0;
        	};
        	function getUserDetail(){
        		$scope.ajaxData.bizContent={
        			loginName:$scope.name
        		};
        		$scope.camel.ajax("POST",str+"getUserDetailBylogin",$scope.ajaxData,getUserDetailSuc,$scope.showMessageErr);
        	}
        	function getUserDetailSuc(data){
                if(data && data.data && (data.data.resultCode==40004||data.data.resultCode==40038)){
                    $("#ajax-alert-info").html(data.data.resultMsg);
                    $scope.show_alert($("#ajax-alert"));
                    $scope.timeout();
                    return;
                }
        		if(data && data.status=="SUCCESS"){
        			$scope.userInfo=data.data.loginUserDetail;
        		}else{
        			$("#ajax-alert-info").html(data.detail);
        			$scope.show_alert($("#ajax-alert"));
        		}
        		$scope.$apply();
        	}
        	getUserDetail();
        	$scope.pwd={
        		old:"",
        		new:"",
        		again:""
        	};
        	$scope.pwdVi={
        		new:0,
        		old:0,
        		again:0,
        		again_1:0,
        		newVi:{
        			focus:function(){
        				$scope.pwdVi.new=0;
        			},
        			blur:function(){
        				$scope.pwdVi.new=!$scope.vili.passWord($scope.pwd.new);
                        if($scope.pwdVi.new){
                            return;
                        }
                        $scope.pwdVi.again_1=$scope.pwd.new!=$scope.pwd.again;
        			}
        		},
        		oldVi:{
        			focus:function(){
        				$scope.pwdVi.old=0;
        			},
        			blur:function(){
        				$scope.pwdVi.old=!$scope.vili.passWord_1($scope.pwd.old);
        			}
        		},
        		againVi:{
        			focus:function(){
        				$scope.pwdVi.again=0;
        				$scope.pwdVi.again_1=0;
        			},
        			blur:function(){
        				$scope.pwdVi.again_1=$scope.pwd.new!=$scope.pwd.again;
        			}
        		}
        	};
        	$scope.modifyPwd=function(){
        		$scope.modify=1;
        	};
        	$scope.submit=function(){
                $scope.pwdVi.oldVi.blur();
                if($scope.pwdVi.old){
                    return;
                }
        		$scope.pwdVi.newVi.blur();
                if($scope.pwdVi.new){
                    return;
                }
                $scope.pwdVi.againVi.blur();
                if($scope.pwdVi.again){
                    return;
                }
                if($scope.pwdVi.again){
                    return;
                }
        		if($scope.pwdVi.new+$scope.pwdVi.old+$scope.pwdVi.again+$scope.pwdVi.again_1>0){
        			return;
        		}
        		$scope.errTip.disabled=1;
        		$scope.ajaxData.bizContent={
        			executorCode:$scope.userInfo.executorUser.executorCode,
        			oriPassWord:$scope.pwd.old,
        			aimsPassWord:$scope.pwd.new
        		};
        		$scope.camel.ajax("POST",str+"changePassWord",$scope.ajaxData,changePwdSuc,$scope.showMessageErr);
        	}
        	function changePwdSuc(data){
                if(data && data.data && (data.data.resultCode==40004||data.data.resultCode==40038)){
                    $("#ajax-alert-info").html(data.data.resultMsg);
                    $scope.show_alert($("#ajax-alert"));
                    $scope.errTip.disabled=0;
                    $scope.timeout();
                    return;
                }
        		if(data && data.status=="SUCCESS"){
        			$scope.init();
        			$("#ajax-alert-info").html("密码修改成功");
                    $timeout($scope.goLogin(),3000);
        		}else{
        			$("#ajax-alert-info").html(data.data.resultMsg);
        		}
        		$scope.show_alert($("#ajax-alert"));
        		$scope.errTip.disabled=0;
        		$scope.$apply();
        	}
        }
    ])
});